In [1]:
# Numpy é uma biblioteca/módulo do python que tem por objetivo fazer calculos matemáticos em estruturas de dados chamadas de arrays

import numpy as np

In [2]:
# Criando um array de 1 dimensão - vetor 
lista = [1, 2, 3, 4, 5]

array = np.array(lista)
print(type(lista))
print(type(array))

arr_zeros = np.zeros(10)
print(arr_zeros)

<class 'list'>
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Criando um array de 2 dimensões - matriz

matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
## notas dos alunos

lista_de_notas = [9.8, 10, 5.6, 9.1]
notas = np.array(lista_de_notas)

In [5]:
print("Máximo: ", notas.max())
print("Mínimo: ", notas.min())
print("Média: ", notas.mean())
print("Desvio Padrão: ", notas.std())
print("Posição menor", notas.argmin())

Máximo:  10.0
Mínimo:  5.6
Média:  8.625
Desvio Padrão:  1.7781661902083283
Posição menor 2
